"""add good to go out column

Revision ID: a9e8a73ee222
Revises: ab78f0942025
Create Date: 2026-04-27 00:00:25.563878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e8a73ee222'
down_revision: Union[str, Sequence[str], None] = 'ab78f0942025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wind', sa.Column('is_good_to_go_out', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wind', 'is_good_to_go_out')
    # ### end Alembic commands ###
