"""move wind to separate table

Revision ID: ab78f0942025
Revises: 1458787a732c
Create Date: 2026-04-26 23:20:07.847553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab78f0942025'
down_revision: Union[str, Sequence[str], None] = '1458787a732c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.create_table(
        'wind',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('wind_mph', sa.Float(), nullable=True),
        sa.Column('wind_kph', sa.Float(), nullable=True),
        sa.Column('wind_degree', sa.Integer(), nullable=True),
        sa.Column(
            'wind_direction',
            postgresql.ENUM(
                'N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE',
                'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW',
                name='winddirection',
                create_type=False
            ),
            nullable=True
        ),
        sa.Column('gust_mph', sa.Float(), nullable=True),
        sa.Column('gust_kph', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_wind_id'), 'wind', ['id'], unique=False)

    op.add_column('weather', sa.Column('wind_id', sa.Integer(), nullable=True))

    op.execute("""
        INSERT INTO wind (
            wind_mph,
            wind_kph,
            wind_degree,
            wind_direction,
            gust_mph,
            gust_kph
        )
        SELECT
            wind_mph,
            wind_kph,
            wind_degree,
            wind_direction,
            gust_mph,
            gust_kph
        FROM weather
        ORDER BY id
    """)

    op.execute("""
        UPDATE weather
        SET wind_id = wind.id
        FROM wind
        WHERE wind.id = weather.id
    """)

    op.create_foreign_key(
        'fk_weather_wind',
        'weather',
        'wind',
        ['wind_id'],
        ['id']
    )

    op.drop_column('weather', 'wind_degree')
    op.drop_column('weather', 'gust_kph')
    op.drop_column('weather', 'gust_mph')
    op.drop_column('weather', 'wind_mph')
    op.drop_column('weather', 'wind_kph')
    op.drop_column('weather', 'wind_direction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('wind_direction', postgresql.ENUM('N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW', name='winddirection'), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('wind_kph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('wind_mph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('gust_mph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('gust_kph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('weather', sa.Column('wind_degree', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'weather', type_='foreignkey')
    op.drop_column('weather', 'wind_id')
    op.drop_index(op.f('ix_wind_id'), table_name='wind')
    op.drop_table('wind')
    # ### end Alembic commands ###
